- .gitignore
- BLUE_HAT_ERD.drawio
- CDTest
- app.js
- package-lock.json
- package.json
- public/index.html
- public/stylesheets/cover.css
- routes/nft.js
- routes/users.js
- src/config.js
- views/error.jade
- views/index.jade
- views/layout.jade
> Remove useless folder

- app.js
- controllers/auth.ctrl.js
- controllers/users.ctrl.js
- routes/auth.js
- routes/index.js
- routes/users.js
- utils/auth.utils.js
- routes 폴더: 가독성을 위해 컨트롤러 연결만 수행
- controllers 폴더: 실제 컨트롤러 함수가 들어감
- utils 폴더: 컨트롤러에서 사용되는 모듈 함수들 넣기
예시로 user.ctrl.js 랑 auth.ctrl.js, auth.utils.js 작성했습니다. 한번 구조 살펴보세요~!
> Orgainze Folder Structure

- app.js
- controllers/auth.ctrl.js
- package-lock.json
- package.json
- routes/auth.js
- utils/auth.utils.js
- views/email.ejs
- mailgun - api 기반 이메일 전송 < no-reply@bluehat.games>
- Email 기반 암호화하여 인증키 생성 - 추후, Redis로 캐싱 필요
To Do
> Implement Email Login Function

- controllers/users.ctrl.js
- models/user.js
- package-lock.json
- package.json
- routes/users.js
- POST /users 라우터 구현 (user 테이블에 row 추가)
- 전역변수 활용하여 verified 여부 파악
- req.body로 email, wallet_address 받음, 아직 wallet_address는 활용하지 않음
- nodemon 설치, npm start시 nodemon 실행
> Implement creating user function, install nodemon

- controllers/auth.ctrl.js
- controllers/users.ctrl.js
- utils/auth.utils.js
- Email 인증 주소 변경(실서버 주소로)
- Dup인 경우 로그인 처리
- Email 전송 실패 케이스 분류
> Fix email verification url, change login status

- BLUE_HAT_ERD.drawio
- bin/www
- controllers/auth.ctrl.js
- controllers/users.ctrl.js
- models/user.js
- package.json
- 유저테이블에 username, wallet_address 추가
- npm restart 구문으로 pm2 실행, 시간값 포함한 로그 기록 (일단 임시로 pm2활용, 추후 winston으로 교체)
> change user table definition, make "npm restart" to log by pm2

- bin/www
- controllers/users.ctrl.js
1. user 테이블 명세 변경
2. npm restart 명령어 수정
3. response시 msg 객체 형태로 반환
> log using pm2, unifying response format

- app.js
- controllers/animal.ctrl.js
- routes/animal.js
신규 기능
- 무작위 동물 생성
- 유저 보유 동물 확인
버그 수정
- 에러 페이지 로딩 불가 문제 해결
> Feat : get random animal, get user animal

- controllers/animal.ctrl.js
- controllers/users.ctrl.js
- message/msg_error.js
- middlewares/verify.js
- models/user.js
- package.json
- routes/animal.js
- routes/users.js
- utils/verify.js
- JWT 인증 추가
- 유저이름 Null 허용
- 유저 삭제 API 추가(테스트용)
> Feat : Add jwt authorization

- controllers/users.ctrl.js
> Fix: error msg

- controllers/users.ctrl.js
> Fix : auth acess token

- app.js
- config/logger.js
- controllers/animal.ctrl.js
- controllers/auth.ctrl.js
- controllers/users.ctrl.js
- message/msg_error.js
- models/animal_possession.js
- models/noun_name.js
- package-lock.json
- package.json
- routes/animal.js
- src/config.js
- test/app.test.js
1. DB명세 변경
2. 테스트 코드 작성 : jest 활용 (npm test 명령어로 테스트 실행)
3. winston 라이브러리 활용한 로깅 시스템 적용
4. 기타 자잘한 수정 사항
> change DB table constraints and name, apply TDD, add logger

- controllers/animal.ctrl.js
- Change JSON Format
- nft_hash : null
> HOTFIX : Change JSON Format

- app.js
- controllers/market.ctrl.js
- routes/market.js
- Market 동물 조회 API 생성
- Market 동물 거래 API 생성
> FEAT : get all nft market animal

- controllers/market.ctrl.js
- controllers/users.ctrl.js
-이메일로만 로그인 처리 허용
-Market Animal 조회시 username return
> Fix : Login only using email-check parameter later

- .gitignore
- controllers/users.ctrl.js
- message/msg_error.js
- middlewares/verify.js
- models/animal_possession.js
- models/market.js
- models/user.js
- routes/users.js
- 유저 삭제 로직 변경
- 유저정보 획득 API
- 유저이름 수정 API
- Market Model 추가
- 삭제시 null -> Cascade 변경
> Feat : User info get, change, delete

- controllers/market.ctrl.js
- models/market.js
- routes/market.js
- 마켓 판매 업로드 API
- 마켓 Animal 조회 API 수정
- 마켓 Animal 조회 가격순 정렬 추가
> Feat: Market sell api

- controllers/market.ctrl.js
- routes/market.js
- 마켓 전체 동물 개수 조회 API
- 마켓 Animal 세부 조회 API
- 마켓 View Count 추가
> Feat : Market Animal count, detail

- controllers/market.ctrl.js
- routes/market.js
- 마켓 동물 구매 로직 추가
- NFT 처리 X, 단순 구매 로직
> Feat : Add buy animal nft logic

- models/user.js
1. User 테이블에 unique 제약 조건이 계속 쌓여 models 폴더의 user 테이블에서 unique 속성을 제거함. 워크벤치에서 직접 유니크 제약 걸어줌
> Remove unique constraint of User table

- controllers/market.ctrl.js
- controllers/nft.ctrl.js
- routes/nft.js
> Fix : Fix order info

- app.js
- controllers/animal.ctrl.js
- message/msg_error.js
- utils/nft.utils.js
> Fix : Err msg, get user animal

- app.js
> HotFix : import change

- controllers/nft.ctrl.js
> Fix: change response status

- controllers/market.ctrl.js
- controllers/users.ctrl.js
- routes/market.js
- utils/nft.utils.js
- NFT 거래 테스트 API 생성(DB 구조 변경상 테스트 우선 생성)
- 유저정보 Update API 수정(계정 생성일, 판매 동물 개수)
> Feat : Nft Trade Test and Get user info update

- config/logger.js
- models/transaction.js
1. log 시간값 한국시간으로 설정
2. transcation table 명세
> Set Winstion logger Timezone, make transaction table

- controllers/nft.ctrl.js
- routes/nft.js
- utils/nft.utils.js
- NFT Symbol 변경
- MetaData Url 생성
> Fix : Change Symbol, Change Metadata url

- README.md
- controllers/nft.ctrl.js
- models/transaction.js
- IPFS MetaData Return
- DB IPFS hash 추가
> Feat : IPFS MetaData Return

- controllers/auth.ctrl.js
- utils/users.utils.js
> Hotfix : internal variable fix

- controllers/users.ctrl.js
- routes/users.js
> Feat : update-coin added

- .dockerignore
- Dockerfile
- controllers/nft.ctrl.js
- docker-compose.yml
- middlewares/file.js
- models/animal_possession.js
- package-lock.json
- package.json
- routes/nft.js
- utils/redis.js
> Docker 적용, IPFS 파일 업로드 적용

- .gitignore
- controllers/nft.ctrl.js
- routes/nft.js
- utils/nft.utils.js
- IPFS 업로드, 민팅 기능 통합
- IPFS 이미지 업로드 및 메타 정보 파일 생성
> Ipfs and minting feature merge

- docker-compose.yml
- nginx/Dockerfile
- nginx/nginx.conf
> Feat : Add ngnix to docker

- test/app.test.js
테스트코드 포맷 작성 (jwt 토큰, 인증 완료된 이메일 필요)
> Test: make describe code, requirement format

- message/msg_error.js
- Fix notEnoughCoin Err msg Return
> Fix : Add notEnoughCoin Err msg

- controllers/animal.ctrl.js
- routes/animal.js
> Feat : update animal info

- utils/auth.utils.js
- Error in auth.utils.js when set user email to redis 
- Change value type bool to stirng, because of redis doesn't support bool type
https://redis.io/docs/data-types/
> Fix: Redis not support bool type

- controllers/nft.ctrl.js
- utils/color.utils.js
- utils/redis.js
- animal_possession 테이블에 동일한 animal_type 과 color 가 없도록 중복검사
- 색상 결정 확률: 첫번째 animal의 색상 값(33%) or 두번째 animal의 색상값(33%) or 전혀 새로운 색상값(33%)
> Feat: MergeAnimal - check if color is duplicated or not

- utils/redis.js
redis creatClient 함수 로컬, 도커 환경 분리
> Fix: createClient - apply redis url

- controllers/market.ctrl.js
- routes/market.js
getMarketDetail api에서 color 함께 리턴하기
> Feat: get market detail detail with color

- controllers/animal.ctrl.js
- controllers/market.ctrl.js
- controllers/nft.ctrl.js
- models/animal.js
- models/animal_possession.js
- utils/color.utils.js
-색변경 api
- animal_possession 테이블 컬럼명 변경(animal_id -> animal_type)
> change color, fix column name

- controllers/animal.ctrl.js
- controllers/nft.ctrl.js
- utils/color.utils.js
> Feat: make animal with default color

- routes/nft.js
> Chore: change routes of merge animal

- controllers/animal.ctrl.js
- utils/color.utils.js
- merge animal 시 animal possession 테이블에 없는 동물 merge 한 경우 예외처리
- 색상 알고리즘 변경 (시간값 기반 랜덤 생성 -> 무작위 랜덤)
> add error handling & change color-changing algorithm

- Dockerfile
> Fix: Dockerfile - npm to apt-get

- Dockerfile
- controllers/animal.ctrl.js
> Feat: change response of mergeAnimal api

- controllers/animal.ctrl.js
- controllers/market.ctrl.js
Transaction / commit / rollback 구현
> Apply Transaction

- app.js
- controllers/animal.ctrl.js
- controllers/auth.ctrl.js
- controllers/hat.ctrl.js
- controllers/market.ctrl.js
- controllers/nft.ctrl.js
- controllers/user.ctrl.js
- utils/color.utils.js
- utils/nft.utils.js
1. original Url 로깅
2. merge animal 색 변경 로직 수정
> change MergeAnimal color logic

- controllers/user.ctrl.js
- models/user.js
> Change When SignUp get walletaddr

- utils/hat.utils.js
> Feat: decrease probability of getting bluehat

- controllers/hat.ctrl.js
유저 검증 로직 추가
hat의 filename 리턴하기
> Change New Hat api

- controllers/market.ctrl.js
Market all animal return animal type and animal head item
> HotFix : All market animal info return

- controllers/user.ctrl.js
- models/user.js
- routes/user.js
- Egg 업데이트 API 추가
- 유저 정보 조회시 egg값 가져옴
> Feat: add update egg api

- utils/color.utils.js
> Feat: convert to pastel color

- app.js
- controllers/wallet.ctrl.js
- package-lock.json
- package.json
- routes/wallet.js
- utils/config.js
- utils/nft.utils.js
- Add create wallet, auto faucet 150 klay
- Fix minting Err, Because of change caver api
> Create wallet and change err

- controllers/animal.ctrl.js
- routes/animal.js
다른 유저의 동물 정보 반환 by animal_possession id
> Feat: get one specific animal information

- controllers/user.ctrl.js
- routes/user.js
egg, coin 동시 증가 api
멀티플레이, 퀘스트 완료 시 활용할 수 있음
> Feat: update egg and coin together

- views/email/signup.ejs
> Fix: change to utf-8
